backend:
  name: git-gateway
  branch: dev
  repo: github.com/NJG-connect/bina-web/
  # display_url: https://confident-bardeen-72ada4.netlify.app/
  # site_url: https://confident-bardeen-72ada4.netlify.app/

media_folder: "static/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images"


collections:
- name: "Data" # Used in routes, e.g., /admin/collections/blog
  label: "Data" # Used in the UI
  files: # The path to the folder where the documents are stored
    - label: "Data"
      name: "data"
      file: "src/data/data.json"
      format: "json"
      create: true # Allow users to create new documents in this collection
      slug: "data" # Filename template, e.g., YYYY-MM-DD-title.md
      fields: # The fields for each document, usually in front matter
        - label: "Header"
          name: "Header"
          widget: "object"
          collapsed: true
          fields: 
          - { label: Image de Fond, name: background, widget: string }
          - label: "Titre"
            name: "title"
            widget: "object"
            collapsed: true
            fields:
              - { label: Ligne 1, name: line1, widget: string }
              - { label: Ligne 2, name: line2, widget: string }
        - label: "Savoir-faire"
          name: "skills"
          widget: "object"
          collapsed: true
          fields: 
          - { label: Texte 1, name: text1, widget: string }
          - { label: Texte 2, name: text2, widget: string }
          - { label: Titre, name: title, widget: string }
          - { label: Gif, name: gif, widget: string }
          - label: Compétences
            name: skill
            widget: list
            fields:
            - { label: "Titre", name: "title", widget: "string" }
            - { label: "Nom de l'icon", name: "icon", widget: "string" }

        - label: "Footer"
          name: "Footer"
          widget: "object"
          collapsed: true
          fields: 
          - { label: Email, name: mail, widget: string }
          - { label: Copyright, name: copyright, widget: string }
          - { label: Titre, name: title, widget: string }
          - { label: Gif, name: gif, widget: string }
          - label: Social Info
            name: social
            widget: list
            fields:
            - { label: "Titre", name: "title", widget: "string" }
            - { label: "Lien", name: "link", widget: "string" }
            - { label: "Icon", name: "icon", widget: "string" }
          - label: Complement
            name: additionalLink
            widget: list
            fields:
            - { label: "Titre", name: "title", widget: "string" }
            - { label: "Lien", name: "link", widget: "string" }

        - label: "Contact"
          name: "Contact"
          widget: "object"
          collapsed: true
          fields: 
          - { label: Photo de Couverture, name: background, widget: string }
          - { label:  Titre, name: title, widget: string }
          - { label: Sous-Titre, name: subtitle, widget: string }
